# Generated by Django 3.0.8 on 2020-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='bank_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='bank card number'),
        ),
    ]
