# Generated by Django 3.0.8 on 2020-09-15 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costumer', '0002_auto_20200912_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='bank_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='bank card number'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='job',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='national_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='national code'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
