# Generated by Django 3.0.8 on 2020-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0002_auto_20200821_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='national_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='national code'),
        ),
    ]
