# Generated by Django 3.0.8 on 2020-09-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0003_auto_20200915_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={'verbose_name': 'costumer', 'verbose_name_plural': 'costumers'},
        ),
    ]
