# Generated by Django 3.0.8 on 2020-09-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('specification', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=250, verbose_name='english name of brand')),
                ('persian_name', models.CharField(max_length=250, verbose_name='persian name of brand')),
                ('image', models.ImageField(upload_to='', verbose_name='image of brand')),
                ('type', models.CharField(choices=[('IR', 'iranian brand'), ('EN', 'foreign brand')], default='IR', max_length=2, verbose_name='type of brand')),
                ('brand_description', models.TextField()),
                ('logo', models.ImageField(height_field=600, help_text='height and width 600 X 600 px', upload_to='', verbose_name='logo of brand', width_field=600)),
                ('judiciary_brand_registration_form', models.ImageField(upload_to='')),
                ('judiciary_site_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of color')),
                ('hex_code', models.CharField(max_length=250, verbose_name='code of color')),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('length', models.PositiveIntegerField(verbose_name='length')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of type')),
                ('value', models.CharField(max_length=250, verbose_name='value of type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=250, verbose_name='english name of product')),
                ('persian_name', models.CharField(max_length=250, verbose_name='persian name of product')),
                ('is_fake', models.BooleanField(verbose_name='originality of product')),
                ('description_of_product', models.TextField(verbose_name='description of product')),
                ('positive_points', models.CharField(max_length=250, verbose_name='positive points')),
                ('negative_points', models.CharField(max_length=250, verbose_name='negative points')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_informations', to='product.Brand', verbose_name='brand')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_informations', to='product.Packaging', verbose_name='packaging')),
                ('type_of_product', models.ManyToManyField(to='product.TypeOfProduct', verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150, verbose_name='tag of product')),
                ('images', models.ImageField(upload_to='', verbose_name='images of product')),
                ('price', models.CharField(max_length=50, verbose_name='price of product')),
                ('discount', models.CharField(max_length=3, verbose_name='discount')),
                ('guarantee', models.CharField(max_length=150, verbose_name='name of guarantee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='category.Category', verbose_name='category')),
                ('colors', models.ManyToManyField(to='product.Color', verbose_name='colors')),
                ('product_information', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.ProductInformation', verbose_name='information of product')),
                ('sellers', models.ManyToManyField(related_name='products', to='seller.Seller', verbose_name='sellers')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='specification.Specification', verbose_name='specification')),
            ],
        ),
    ]
