# Generated by Django 3.0.8 on 2020-09-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0002_auto_20200916_1246'),
        ('category', '0004_auto_20200920_0746'),
        ('specification', '0006_auto_20200919_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=250, verbose_name='english name of brand')),
                ('persian_name', models.CharField(max_length=250, verbose_name='persian name of brand')),
                ('image', models.ImageField(upload_to='images', verbose_name='image of brand')),
                ('type', models.CharField(choices=[('IR', 'iranian brand'), ('EN', 'foreign brand')], default='IR', max_length=2, verbose_name='type of brand')),
                ('brand_description', models.TextField()),
                ('logo', models.ImageField(height_field=600, help_text='height and width 600 X 600 px', upload_to='images', verbose_name='logo of brand', width_field=600)),
                ('judiciary_brand_registration_form', models.ImageField(upload_to='images')),
                ('judiciary_site_link', models.URLField()),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of color')),
                ('hex_code', models.CharField(max_length=250, verbose_name='code of color')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(verbose_name='width')),
                ('height', models.PositiveIntegerField(verbose_name='height')),
                ('length', models.PositiveIntegerField(verbose_name='length')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
            ],
            options={
                'verbose_name': 'packing',
                'verbose_name_plural': 'packaging',
            },
        ),
        migrations.CreateModel(
            name='TypeOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name of type')),
                ('value', models.CharField(max_length=250, verbose_name='value of type')),
            ],
            options={
                'verbose_name': 'product type',
                'verbose_name_plural': 'product types',
            },
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=250, verbose_name='english name of product')),
                ('persian_name', models.CharField(max_length=250, verbose_name='persian name of product')),
                ('is_fake', models.BooleanField(verbose_name='originality of product')),
                ('description_of_product', models.TextField(blank=True, null=True, verbose_name='description of product')),
                ('positive_points', models.CharField(blank=True, max_length=250, null=True, verbose_name='positive points')),
                ('negative_points', models.CharField(blank=True, max_length=250, null=True, verbose_name='negative points')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_informations', to='product.Brand', verbose_name='brand')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_informations', to='product.Packaging', verbose_name='packaging')),
                ('type_of_product', models.ManyToManyField(to='product.TypeOfProduct', verbose_name='type')),
            ],
            options={
                'verbose_name': 'product information',
                'verbose_name_plural': 'product informations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150, verbose_name='tag of product')),
                ('images', models.ImageField(upload_to='images', verbose_name='images of product')),
                ('price', models.CharField(max_length=50, verbose_name='price of product')),
                ('discount', models.CharField(blank=True, max_length=3, null=True, verbose_name='discount')),
                ('guarantee', models.CharField(blank=True, max_length=150, null=True, verbose_name='name of guarantee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='category.Category', verbose_name='category')),
                ('colors', models.ManyToManyField(to='product.Color', verbose_name='colors')),
                ('product_information', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.ProductInformation', verbose_name='information of product')),
                ('sellers', models.ManyToManyField(related_name='products', to='seller.Seller', verbose_name='sellers')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='specification.Specification', verbose_name='specification')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
