# Generated by Django 3.0.8 on 2020-09-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='packaging',
            options={'verbose_name': 'packing', 'verbose_name_plural': 'packaging'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productinformation',
            options={'verbose_name': 'product information', 'verbose_name_plural': 'product informations'},
        ),
        migrations.AlterModelOptions(
            name='typeofproduct',
            options={'verbose_name': 'product type', 'verbose_name_plural': 'product types'},
        ),
    ]
