# Generated by Django 3.0.8 on 2020-09-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200916_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name of guarantee'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_informations', to='product.Brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='description_of_product',
            field=models.TextField(blank=True, null=True, verbose_name='description of product'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='negative_points',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='negative points'),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='positive_points',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='positive points'),
        ),
    ]
