# Generated by Django 3.0.8 on 2020-09-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200920_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='image of brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='judiciary_brand_registration_form',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(height_field=600, help_text='height and width 600 X 600 px', upload_to='images', verbose_name='logo of brand', width_field=600),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='images', verbose_name='images of product'),
        ),
    ]
