# Generated by Django 3.0.8 on 2020-09-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'seller', 'verbose_name_plural': 'sellers'},
        ),
    ]
