# Generated by Django 3.0.8 on 2020-09-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'specification', 'verbose_name_plural': 'specifications'},
        ),
        migrations.AlterField(
            model_name='specification',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='specification.Specification'),
        ),
    ]
