# Generated by Django 3.0.8 on 2020-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0004_auto_20200919_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='value',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='value of specification'),
        ),
    ]
