# Generated by Django 3.0.8 on 2020-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0005_specification_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='value',
        ),
        migrations.AddField(
            model_name='specification',
            name='field_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='name of field'),
        ),
        migrations.AddField(
            model_name='specification',
            name='field_value',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='value of field'),
        ),
    ]
