# Generated by Django 3.0.8 on 2020-09-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20200919_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
