# Generated by Django 3.0.8 on 2020-09-15 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title of comment')),
                ('positive_points', models.CharField(blank=True, max_length=250, verbose_name='positive points')),
                ('negative_points', models.CharField(blank=True, max_length=250, verbose_name='negative points')),
                ('text', models.TextField(verbose_name='text of comment')),
                ('status', models.CharField(choices=[('a', 'accepted'), ('w', 'awaiting approval'), ('n', 'not approved')], default='w', max_length=1, verbose_name='status of comment')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
